apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-amf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.102\"]"
    spec:
      containers:
      - name: myapp-container
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/amf"]
        stdin: true
        tty: true
        volumeMounts:
        - name: amfcfg
          mountPath: /go/src/free5gc/config/amfcfg.conf
          subPath: amfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: amfcfg.conf
            path: amfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
