apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-ausf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-ausf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-ausf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.108\"]"
    spec:
      containers:
      - name: ausf
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/ausf"]
        stdin: true
        tty: true
        volumeMounts:
        - name: ausfcfg
          mountPath: /go/src/free5gc/config/ausfcfg.conf
          subPath: ausfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: ausfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: ausfcfg.conf
            path: ausfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
