apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nrf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.101\"]"
    spec:
      containers:
      - name: myapp-container
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/nrf"]
        stdin: true
        tty: true
        volumeMounts:
        - name: nrfcfg
          mountPath: /go/src/free5gc/config/nrfcfg.conf
          subPath: nrfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: nrfcfg.conf
            path: nrfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
