apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nssf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nssf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.107\"]"
    spec:
      containers:
      - name: nssf
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/nssf"]
        stdin: true
        tty: true
        volumeMounts:
        - name: nssfcfg
          mountPath: /go/src/free5gc/config/nssfcfg.conf
          subPath: nssfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: nssfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: nssfcfg.conf
            path: nssfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
