apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udm-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udm
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.106\"]"
    spec:
      containers:
      - name: udm
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/udm"]
        stdin: true
        tty: true
        volumeMounts:
        - name: udmcfg
          mountPath: /go/src/free5gc/config/udmcfg.conf
          subPath: udmcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: udmcfg.conf
            path: udmcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
