apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udr-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udr
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udr
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.104\"]"
    spec:
      containers:
      - name: myapp-container
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/udr"]
        stdin: true
        tty: true
        volumeMounts:
        - name: udrcfg
          mountPath: /go/src/free5gc/config/udrcfg.conf
          subPath: udrcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: udrcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: udrcfg.conf
            path: udrcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
