apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.109\"]"
    spec:
      containers:
      - name: myapp-container
        image: tschchin/free5gc-control:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/upf"]
        stdin: true
        tty: true
        volumeMounts:
        - name: upfcfg
          mountPath: /go/src/free5gc/config/upfcfg.conf
          subPath: upfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: upfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: upfcfg.conf
            path: upfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
