apiVersion: v1
kind: Service
metadata:
  name: upf1-svc
spec:
  type: NodePort
  ports:
  - port: 30003
    targetPort: 2152
    nodePort: 30003
    protocol: UDP
  selector:
    app: free5gc-upf1-deployment
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-upf1-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.109\"]"
    spec:
      containers:      
      - name: upf1
        image: tschchin/free5gc-user:latest
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "./bin/free5gc-upfd"]
        stdin: true
        tty: true
        volumeMounts:
          - name: upfcfg
            mountPath: /go/src/free5gc/src/upf/build/config/upfcfg.yaml
            subPath: upfcfg.yaml
          - name: free5gc
            mountPath: /go/src/free5gc/config/free5GC.conf
            subPath: free5GC.conf
      volumes:
        - name: upfcfg
          configMap:
            name: free5gc-configmap
            items: 
              - key: upfcfg1.yaml
                path: upfcfg.yaml
        - name: free5gc
          configMap:
            name: free5gc-configmap
            items: 
              - key: free5GC.conf
                path: free5GC.conf
