apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.202.111\"]"
    spec:
      containers:      
      - name: upf3
        image: tschchin/free5gc-user:latest
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "./bin/free5gc-upfd"]
        stdin: true
        tty: true
        volumeMounts:
          - name: upfcfg
            mountPath: /go/src/free5gc/src/upf/build/config/upfcfg.yaml
            subPath: upfcfg.yaml
          - name: free5gc
            mountPath: /go/src/free5gc/config/free5GC.conf
            subPath: free5GC.conf
      volumes:
        - name: upfcfg
          configMap:
            name: free5gc-configmap
            items: 
              - key: upfcfg3.yaml
                path: upfcfg.yaml
        - name: free5gc
          configMap:
            name: free5gc-configmap
            items: 
              - key: free5GC.conf
                path: free5GC.conf
